# NumPy Fundamentals
This notebook reviews the core NumPy concepts that form the foundation of scientific computing and machine learning in Python. NumPy provides efficient multidimensional arrays and optimized numerical operations that are significantly faster than standard Python data structures. The topics covered in this notebook—including arrays, indexing and slicing, broadcasting, and vectorized operations—will be used extensively throughout this research project for data preprocessing, mathematical computation, and implementing machine learning models.

## Arrays

NumPy's primary data structure is the **ndarray**, an N-dimensional array designed for efficient numerical computation. Unlike Python lists, NumPy arrays store elements of the same data type in contiguous memory, allowing mathematical operations to be performed much more efficiently. Arrays can represent vectors, matrices, images, and higher-dimensional tensors, making them the foundation of nearly all scientific computing libraries in Python.


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

matrix = np.arange(1,13).reshape(3,4)

print(matrix)
print(matrix.shape)

[1 2 3 4 5]
(5,)
1
int64
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


## Indexing and Slicing

Indexing and slicing provide efficient ways to access and manipulate subsets of NumPy arrays. These operations allow individual elements, rows, columns, or sections of an array to be selected without unnecessary copying of data. Mastering indexing and slicing is essential for filtering datasets, selecting features, and preparing data for machine learning models.

In [5]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix[0])
print(matrix[:,1])
print(matrix[1:,0:2])

arr = np.array([3,8,1,9,5])

print(arr[arr > 4])

[1 2 3]
[2 5 8]
[[4 5]
 [7 8]]
[8 9 5]


## Broadcasting

Broadcasting is NumPy's mechanism for performing arithmetic operations on arrays with different but compatible shapes. Instead of requiring explicit loops or duplicated data, NumPy automatically expands smaller arrays during computation whenever possible. Broadcasting enables concise, readable, and highly efficient numerical code.

In [8]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

vector = np.array([10,20,30])

print(matrix + vector)

scores = np.array([70,82,91])

print(scores + 5)

[[11 22 33]
 [14 25 36]]
[75 87 96]


## Vectorized Operations

Vectorization refers to performing operations on entire arrays at once rather than iterating through individual elements with Python loops. Because these operations are implemented in optimized low-level code, vectorized computations are significantly faster and more expressive. Most numerical algorithms in machine learning rely heavily on vectorized operations for both performance and readability.

In [15]:
arr = np.array([1, 2, 3, 4])

print(arr * 2)    
print(arr + 10) 

arr2 = np.array([10, 20, 30, 40])
print(arr + arr2)

matrix = np.array([[1, 2], [3, 4]])

print(np.sum(matrix))
print(np.mean(matrix, axis=0)) # Column averages

[2 4 6 8]
[11 12 13 14]
[11 22 33 44]
10
[2. 3.]


## Practice Data Analysis with Numpy

In [18]:
import numpy as np

np.random.seed(42)

num_students = 30
num_questions = 20

# Create student data randomly
scores = np.random.choice(
    [0, 1],
    size=(num_students, num_questions),
    p=[0.35, 0.65]
)

print("Dataset Shape:", scores.shape)
print(scores)

# Average of student scores
overall_accuracy = scores.mean()
print(f"\nOverall Class Accuracy: {overall_accuracy:.2%}")


# Student stats
student_accuracy = scores.mean(axis=1)

highest_student = np.argmax(student_accuracy)
lowest_student = np.argmin(student_accuracy)

print("\nStudent Accuracy")
for i, accuracy in enumerate(student_accuracy):
    print(f"Student {i+1}: {accuracy:.2%}")

print(f"\nHighest Performing Student: Student {highest_student+1}")
print(f"Lowest Performing Student: Student {lowest_student+1}")


# Question stats
question_accuracy = scores.mean(axis=0)

easiest_question = np.argmax(question_accuracy)
hardest_question = np.argmin(question_accuracy)

print("\nQuestion Correctness")

for i, accuracy in enumerate(question_accuracy):
    print(f"Question {i+1}: {accuracy:.2%}")

print(f"\nEasiest Question: Question {easiest_question+1}")
print(f"Hardest Question: Question {hardest_question+1}")


# Scores
student_scores = scores.sum(axis=1)

print("\nStudent Scores")

for i, score in enumerate(student_scores):
    print(f"Student {i+1}: {score}/{num_questions}")

# Distribution
print("\nSummary Statistics")

print(f"Average Score: {student_scores.mean():.2f}")
print(f"Median Score: {np.median(student_scores):.2f}")
print(f"Highest Score: {student_scores.max()}")
print(f"Lowest Score: {student_scores.min()}")
print(f"Standard Deviation: {student_scores.std():.2f}")

# Students above average
above_average = np.where(student_scores > student_scores.mean())[0]

print("\nStudents Above Average")

for student in above_average:
    print(f"Student {student+1}")

# Hard questions
hard_questions = np.where(question_accuracy < 0.50)[0]

print("\nQuestions With Less Than 50% Accuracy")

if len(hard_questions) == 0:
    print("None")
else:
    for question in hard_questions:
        print(f"Question {question+1}")


# Perfect scores
perfect_students = np.where(student_scores == num_questions)[0]

print("\nPerfect Scores")

if len(perfect_students) == 0:
    print("No perfect scores.")
else:
    for student in perfect_students:
        print(f"Student {student+1}")

Dataset Shape: (30, 20)
[[1 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0]
 [1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 0 1 1]
 [0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 0 0 0]
 [1 0 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0]
 [1 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0]
 [0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1 1]
 [1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 1 1 1]
 [1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 1 1 0 1]
 [1 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 1 1 1 0]
 [0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1]
 [1 0 0 1 1 0 0 1 0 0 1 1 1 0 1 0 0 1 1 1]
 [1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0]
 [1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0]
 [1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 1 1 0 1 0]
 [0 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 0 0]
 [1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0]
 [1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 0]
 [0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1]
 [0 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1]
 [1 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0]
 [0 1 1 1 1 1 1 1 1 0 1 1 1 1 